export const TAURI_COMMANDS = {
  appInfo: "app_info",
  credentialStatus: "credential_status",
  credentialSet: "credential_set",
  credentialClear: "credential_clear",
  credentialVerify: "credential_verify",
  openRouterModels: "openrouter_models",
  workspaceDefault: "workspace_default",
  workspaceList: "workspace_list",
  workspaceActivate: "workspace_activate",
  workspaceSelect: "workspace_select",
  workspaceGitOverview: "workspace_git_overview",
  pluginList: "plugin_list",
  agentRun: "agent_run",
  agentCancel: "agent_cancel",
  agentApproval: "agent_resolve_approval",
  conversationList: "conversation_list",
  conversationMessages: "conversation_messages",
  conversationCreate: "conversation_create",
  terminalCreate: "terminal_create",
  terminalWrite: "terminal_write",
  terminalResize: "terminal_resize",
  terminalKill: "terminal_kill",
  terminalSubscribe: "terminal_subscribe",
  browserState: "browser_state",
  browserStart: "browser_start",
  browserNavigate: "browser_navigate",
  browserBack: "browser_back",
  browserForward: "browser_forward",
  browserReload: "browser_reload",
  browserMouse: "browser_mouse",
  browserKey: "browser_key",
  browserClose: "browser_close",
  scheduleList: "schedule_list",
  scheduleCreate: "schedule_create",
  scheduleUpdate: "schedule_update",
  scheduleDelete: "schedule_delete",
} as const;

export const TAURI_EVENTS = {
  agent: "agent:event",
  terminal: "terminal:event",
  browser: "browser:event",
} as const;
